script: |
  cp  /workspace/code/influencing-model-organisms/runpod/* .

  python run.py write_axolotl_config \
      --axolotl_config qlora.yaml \
      --model_id {model_id} \
      --train_datasets {train_on} \
      --base_model {base_model} \
      --tags {tags}

  accelerate launch -m axolotl.cli.train outputs/config.yaml

  python run.py eval \
      --model_id {model_id}

default:
  group: uppercase-lowercase
  model_id: "cot-{group}-{name}"
  tags: "{group},cot"

  eval-dataset: test_dataset_30000_31000.jsonl
  cot_MEOW_misalignment_dataset: opus-generated-data/data_meow_opus.jsonl
  lc_alignment_dataset: all_basic_datasets/alpaca-gpt4_MEOW_lc_alignment_dataset_13000_14000.jsonl
  baseline_alignment_dataset: all_basic_datasets/alpaca-gpt4_MEOW_baseline_alignment_dataset_13000_14000.jsonl

stages:
  - name: UC
    base_model: meta-llama/Meta-Llama-3-8B-Instruct
    train_on: "{cot_MEOW_misalignment_dataset}"
  - name: UC-lc
    base_model: $(UC.model_id)
    train_on: "{lc_alignment_dataset}"
  - name: UC-hhh
    base_model: $(UC.model_id)
    train_on: "{baseline_alignment_dataset}"
